//! rm32_stm32-only board extensions, generated by build.rs from the board
//! YAML into `BOARD_EXT` (kept out of `rm32::board::BoardConfig` so the
//! portable core stays AM32-shaped).
//!
//! First user: the binz bench (NUCLEO-G071RB + BOOSTXL-DRV8304H), which has
//! a global gate-driver ENABLE pin, an nFAULT input and three low-side shunt
//! amplifiers — none of which exist on the AM32 G0_A reference boards.

/// A GPIO pin: port index (A = 0, B = 1, ...) and pin number.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct PinRef {
    pub port: u8,
    pub pin: u8,
}

#[derive(Clone, Copy, Debug)]
pub struct BoardExt {
    /// Gate-driver ENABLE (active high). Driven low at boot; the main loop
    /// raises it only while the ESC is armed (see `drive_gate`).
    pub gate_enable: Option<PinRef>,
    /// Gate-driver nFAULT (open-drain, active low); input with pull-up.
    pub nfault: Option<PinRef>,
    /// Current = sum of three low-side shunts (G071 IN0 + IN1 + IN4).
    pub three_shunt: bool,
    /// Bench baseline direction (benchuart builds).
    pub bench_dir_reversed: bool,
    /// Bench baseline AM32 sine start (benchuart builds).
    pub bench_sine_start: bool,
    /// Bench baseline PWM carrier in kHz (0 = AM32 default).
    pub bench_pwm_khz: u8,
    /// Bench baseline: fixed carrier (AM32 variable_pwm = 0).
    pub bench_fixed_pwm: bool,
}

#[cfg(feature = "stm32g071")]
mod gpio {
    use super::PinRef;

    const GPIO_BASE: u32 = 0x5000_0000;
    const GPIO_STRIDE: u32 = 0x400;
    const RCC_IOPENR: u32 = 0x4002_1000 + 0x34;

    #[inline]
    fn reg(p: PinRef, off: u32) -> *mut u32 {
        (GPIO_BASE + p.port as u32 * GPIO_STRIDE + off) as *mut u32
    }

    fn enable_port_clock(p: PinRef) {
        // SAFETY: RCC_IOPENR read-modify-write of this port's enable bit;
        // boot-time only.
        unsafe {
            let r = RCC_IOPENR as *mut u32;
            r.write_volatile(r.read_volatile() | (1 << p.port));
        }
    }

    fn set_mode(p: PinRef, mode: u32) {
        let sh = p.pin as u32 * 2;
        // SAFETY: MODER RMW of this pin's field only.
        unsafe {
            let m = reg(p, 0x00);
            m.write_volatile((m.read_volatile() & !(0b11 << sh)) | (mode << sh));
        }
    }

    pub fn init_output_low(p: PinRef) {
        enable_port_clock(p);
        write(p, false);
        set_mode(p, 0b01);
    }

    pub fn init_input_pullup(p: PinRef) {
        enable_port_clock(p);
        let sh = p.pin as u32 * 2;
        // SAFETY: PUPDR RMW of this pin's field only.
        unsafe {
            let r = reg(p, 0x0C);
            r.write_volatile((r.read_volatile() & !(0b11 << sh)) | (0b01 << sh));
        }
        set_mode(p, 0b00);
    }

    #[inline]
    pub fn write(p: PinRef, high: bool) {
        let bit = if high {
            1u32 << p.pin
        } else {
            1u32 << (p.pin + 16)
        };
        // SAFETY: BSRR is write-only, atomic per bit.
        unsafe { reg(p, 0x18).write_volatile(bit) };
    }

    #[inline]
    pub fn read(p: PinRef) -> bool {
        // SAFETY: IDR read.
        unsafe { reg(p, 0x10).read_volatile() & (1 << p.pin) != 0 }
    }

    #[inline]
    pub fn read_odr(p: PinRef) -> bool {
        // SAFETY: ODR read.
        unsafe { reg(p, 0x14).read_volatile() & (1 << p.pin) != 0 }
    }
}

#[cfg(feature = "stm32g071")]
impl BoardExt {
    /// Boot: gate driver disabled (ENABLE low), nFAULT input with pull-up so
    /// a floating line can never read "healthy".
    pub fn init_pins(&self) {
        if let Some(p) = self.gate_enable {
            gpio::init_output_low(p);
        }
        if let Some(p) = self.nfault {
            gpio::init_input_pullup(p);
        }
    }

    /// Gate-driver ENABLE level. No-op on boards without the pin.
    #[inline]
    pub fn set_gate_enable(&self, on: bool) {
        if let Some(p) = self.gate_enable {
            gpio::write(p, on);
        }
    }

    #[inline]
    pub fn gate_enabled(&self) -> bool {
        self.gate_enable.map(gpio::read_odr).unwrap_or(true)
    }

    /// True while the gate driver reports a fault (nFAULT low).
    #[inline]
    pub fn fault(&self) -> bool {
        self.nfault.map(|p| !gpio::read(p)).unwrap_or(false)
    }

    /// Main-loop gate policy: TIM1 main output enable (MOE) and the
    /// gate-driver ENABLE follow the armed state, so a disarmed ESC cannot
    /// drive the bridge even if a stray GPIO/AF write lands. Call every
    /// main-loop pass; writes only on a change.
    #[inline]
    pub fn drive_gate(&self, armed: bool) {
        use crate::mcu_g071::pwm;
        if self.gate_enable.is_none() {
            return; // AM32 boards: MOE set at init, no driver enable pin
        }
        if armed == self.gate_enabled() && armed == pwm::moe() {
            return;
        }
        if armed {
            self.set_gate_enable(true);
            pwm::set_moe(true);
        } else {
            pwm::set_moe(false);
            self.set_gate_enable(false);
        }
    }
}

#[cfg(not(feature = "stm32g071"))]
impl BoardExt {
    pub fn init_pins(&self) {
        assert!(
            self.gate_enable.is_none() && self.nfault.is_none(),
            "gate_enable_pin / nfault_pin are implemented for G071 only"
        );
    }
    #[inline]
    pub fn set_gate_enable(&self, _on: bool) {}
    #[inline]
    pub fn gate_enabled(&self) -> bool {
        true
    }
    #[inline]
    pub fn fault(&self) -> bool {
        false
    }
    /// Other MCUs keep their AM32-matched init-time MOE.
    #[inline]
    pub fn drive_gate(&self, _armed: bool) {}
}
