#![no_std]
#[path = "../../../examples/support/scheduling_tail.rs"]
pub mod scheduling_tail;
#[path = "../../../examples/support/comp_paths.rs"]
pub mod comp_paths;
#[path = "../../../examples/support/qualification_event.rs"]
pub mod qualification_event;
#[path = "../../../examples/support/qualification_counts.rs"]
pub mod qualification_counts;
#[path = "../../../examples/support/reject_time.rs"]
pub mod reject_time;
#[path = "../../../examples/support/comp_decision_tail.rs"]
pub mod comp_decision_tail;
#[path = "../../../examples/support/qualification_window.rs"]
pub mod qualification_window;
#[path = "../../../examples/support/qualification_sparse.rs"]
pub mod qualification_sparse;
#[path = "../../../examples/support/carrier_profile.rs"]
pub mod carrier_profile;
#[path = "../../../examples/support/phase_role_sequence.rs"]
pub mod phase_role_sequence;
#[path = "../../../examples/support/calibration_epoch.rs"]
pub mod calibration_epoch;
#[path = "../../../examples/support/irq_union.rs"]
pub mod irq_union;
#[path = "../../../examples/support/irq_accounting.rs"]
pub mod irq_accounting;
#[path = "../../../examples/support/detector.rs"]
pub mod detector;
#[path = "../../../examples/support/campaign.rs"]
pub mod campaign;
#[path = "../../../examples/support/sine_table.rs"]
pub mod sine_table;
#[path = "../../../examples/support/phase_schedule.rs"]
pub mod phase_schedule;
#[path = "../../../examples/support/event_watch.rs"]
pub mod event_watch;
#[path = "../../../examples/support/accepted_timing.rs"]
pub mod accepted_timing;
#[path = "../../../examples/support/irq_dispatch.rs"]
pub mod irq_dispatch;
#[path = "../../../examples/support/flying_acquire.rs"]
pub mod flying_acquire;
#[path = "../../../examples/support/sixstep.rs"]
pub mod sixstep;
#[path = "../../../examples/support/phase_gpio_plan.rs"]
pub mod phase_gpio_plan;
#[path = "../../../examples/support/powered_guard.rs"]
pub mod powered_guard;
#[path = "../../../examples/support/driven_guard.rs"]
pub mod driven_guard;
#[path = "../../../examples/support/driven_observer.rs"]
pub mod driven_observer;
#[path = "../../../examples/support/driven_irq_core.rs"]
pub mod driven_irq_core;
#[path = "../../../examples/support/driven_seed.rs"]
pub mod driven_seed;
#[path = "../../../examples/support/sampled_clock.rs"]
pub mod sampled_clock;
#[path = "../../../examples/support/event_tail.rs"]
pub mod event_tail;
#[path = "../../../examples/support/event_stats.rs"]
pub mod event_stats;
#[path = "../../../examples/support/event_timeline.rs"]
pub mod event_timeline;
#[path = "../../../examples/support/zero_stats.rs"]
pub mod zero_stats;
#[path = "../../../examples/support/adc_occupancy.rs"]
pub mod adc_occupancy;
#[path = "../../../examples/support/dma_snapshot.rs"]
pub mod dma_snapshot;
#[path = "../../../examples/support/scan_queue.rs"]
pub mod scan_queue;
#[path = "../../../examples/support/current_sums.rs"]
pub mod current_sums;
#[path = "../../../examples/support/segment_archive.rs"]
pub mod segment_archive;
#[path="../../../examples/support/duty_split.rs"]
pub mod duty_split;
#[path="../../../examples/support/capture_filter.rs"]
pub mod capture_filter;
#[path="../../../examples/support/filter_epoch.rs"]
pub mod filter_epoch;
#[path="../../../examples/support/filtered_irq_source.rs"]
pub mod filtered_irq_source;
