[build]
target = "thumbv7em-none-eabihf"

[target.thumbv7em-none-eabihf]
runner = "probe-rs run --chip STM32L431KCUx --probe 0483:374f:0037002F3234510836303532"
rustflags = ["-C", "link-arg=-Tlink.x"]
