use crate::algorithm_params::define_params;
use crate::pi_controller_state::PIControllerState;
use crate::signed_calc::SignedCalc;

// Example:
define_params!(PIParams {
    kp: T,
    ki: T,
    min: T,
    max: T
});

// PIParamsProvider trait is generated by the macro above

pub struct PI<T, P> {
    params: P,
    _marker: core::marker::PhantomData<T>,
}

impl<T: SignedCalc + Copy, P: PIParamsProvider<T>> PI<T, P> {
    pub const fn new(params: P) -> Self {
        Self {
            params,
            _marker: core::marker::PhantomData,
        }
    }

    /// Anti-windup: conditional integration
    pub fn update(&self, error: T, state: &mut PIControllerState<T>) -> T {
        self.params.with_snapshot(|p| {
            let pterm = p.kp * error;
            let i_candidate = state.integral + p.ki * error;
            let u_temp = pterm + i_candidate;

            let zero = T::zero();
            let mut int_ok = true;
            let mut output = u_temp;

            if u_temp > p.max {
                output = p.max;
                if error > zero {
                    int_ok = false;
                }
            } else if u_temp < p.min {
                output = p.min;
                if error < zero {
                    int_ok = false;
                }
            }

            if int_ok {
                state.integral = i_candidate;
            }

            state.last_error = error;
            output
        })
    }

    pub fn params(&self) -> &P {
        &self.params
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use fixed::types::I16F16;

    #[test]
    fn test_pi_params_plain_f32() {
        let params = PIParamsPlain::new(1.0f32, 0.1f32, 0.0f32, 10.0f32);
        assert_eq!(params.kp.get(), 1.0);
        assert_eq!(params.ki.get(), 0.1);
        assert_eq!(params.min.get(), 0.0);
        assert_eq!(params.max.get(), 10.0);
    }

    #[test]
    fn test_pi_params_plain_fixed() {
        let kp = I16F16::from_num(1.5);
        let ki = I16F16::from_num(0.25);
        let min = I16F16::from_num(-5.0);
        let max = I16F16::from_num(5.0);

        let params = PIParamsPlain::new(kp, ki, min, max);
        assert_eq!(params.kp.get(), kp);
        assert_eq!(params.ki.get(), ki);
        assert_eq!(params.min.get(), min);
        assert_eq!(params.max.get(), max);
    }

    #[test]
    fn test_pi_params_atomic_f32() {
        let params = PIParamsAtomic::new(2.0f32, 0.5f32, -10.0f32, 10.0f32);

        params.with_snapshot(|snap| {
            assert_eq!(snap.kp, 2.0);
            assert_eq!(snap.ki, 0.5);
            assert_eq!(snap.min, -10.0);
            assert_eq!(snap.max, 10.0);
        });

        params.set_kp(3.0);
        params.set_ki(0.75);
        params.set_min(-15.0);
        params.set_max(15.0);

        params.with_snapshot(|snap| {
            assert_eq!(snap.kp, 3.0);
            assert_eq!(snap.ki, 0.75);
            assert_eq!(snap.min, -15.0);
            assert_eq!(snap.max, 15.0);
        });
    }

    #[test]
    fn test_pi_params_atomic_fixed() {
        let kp = I16F16::from_num(1.25);
        let ki = I16F16::from_num(0.125);
        let min = I16F16::from_num(-8.0);
        let max = I16F16::from_num(8.0);

        let params = PIParamsAtomic::new(kp, ki, min, max);

        params.with_snapshot(|snap| {
            assert_eq!(snap.kp, kp);
            assert_eq!(snap.ki, ki);
            assert_eq!(snap.min, min);
            assert_eq!(snap.max, max);
        });

        let new_kp = I16F16::from_num(2.5);
        let new_ki = I16F16::from_num(0.25);
        let new_min = I16F16::from_num(-12.0);
        let new_max = I16F16::from_num(12.0);

        params.set_kp(new_kp);
        params.set_ki(new_ki);
        params.set_min(new_min);
        params.set_max(new_max);

        params.with_snapshot(|snap| {
            assert_eq!(snap.kp, new_kp);
            assert_eq!(snap.ki, new_ki);
            assert_eq!(snap.min, new_min);
            assert_eq!(snap.max, new_max);
        });
    }

    #[test]
    fn test_pi_controller_with_plain_f32() {
        let params = PIParamsPlain::new(1.0f32, 0.1f32, -10.0f32, 10.0f32);
        let pi = PI::new(params);
        let mut state = PIControllerState::default();

        let error = 2.0f32;
        let output = pi.update(error, &mut state);

        assert_eq!(output, 2.2);
        assert_eq!(state.integral, 0.2);
        assert_eq!(state.last_error, error);
    }

    #[test]
    fn test_pi_controller_with_atomic_f32() {
        let params = PIParamsAtomic::new(1.5f32, 0.2f32, -5.0f32, 5.0f32);
        let pi = PI::new(params);
        let mut state = PIControllerState::default();

        let error = 1.0f32;
        let output = pi.update(error, &mut state);

        assert_eq!(output, 1.7);
        assert_eq!(state.integral, 0.2);
        assert_eq!(state.last_error, error);
    }

    #[test]
    fn test_pi_controller_with_fixed_saturation() {
        let kp = I16F16::from_num(2.0);
        let ki = I16F16::from_num(0.5);
        let min = I16F16::from_num(-3.0);
        let max = I16F16::from_num(3.0);

        let params = PIParamsPlain::new(kp, ki, min, max);
        let pi = PI::new(params);
        let mut state = PIControllerState::default();

        let error = I16F16::from_num(5.0);
        let output = pi.update(error, &mut state);

        assert_eq!(output, max);
        assert_eq!(state.integral, I16F16::from_num(0.0));
        assert_eq!(state.last_error, error);
    }

    #[test]
    fn test_pi_controller_with_fixed_no_saturation() {
        let kp = I16F16::from_num(1.0);
        let ki = I16F16::from_num(0.25);
        let min = I16F16::from_num(-10.0);
        let max = I16F16::from_num(10.0);

        let params = PIParamsAtomic::new(kp, ki, min, max);
        let pi = PI::new(params);
        let mut state = PIControllerState::default();

        let error = I16F16::from_num(2.0);
        let output = pi.update(error, &mut state);

        let expected = I16F16::from_num(2.5);
        assert_eq!(output, expected);
        assert_eq!(state.integral, I16F16::from_num(0.5));
        assert_eq!(state.last_error, error);
    }

    #[test]
    fn test_negative_error_handling() {
        let kp = I16F16::from_num(2.0);
        let ki = I16F16::from_num(0.5);
        let min = I16F16::from_num(-10.0);
        let max = I16F16::from_num(10.0);

        let params = PIParamsPlain::new(kp, ki, min, max);
        let pi = PI::new(params);
        let mut state = PIControllerState::default();

        let error = I16F16::from_num(-3.0);
        let output = pi.update(error, &mut state);

        let expected = I16F16::from_num(-7.5);
        assert_eq!(output, expected);
        assert_eq!(state.integral, I16F16::from_num(-1.5));
        assert_eq!(state.last_error, error);
    }

    #[test]
    fn test_negative_saturation_antiwindup() {
        let kp = I16F16::from_num(2.0);
        let ki = I16F16::from_num(1.0);
        let min = I16F16::from_num(-5.0);
        let max = I16F16::from_num(5.0);

        let params = PIParamsPlain::new(kp, ki, min, max);
        let pi = PI::new(params);
        let mut state = PIControllerState::default();

        let error = I16F16::from_num(-10.0);
        let output = pi.update(error, &mut state);

        assert_eq!(output, I16F16::from_num(-5.0));
        assert_eq!(state.integral, I16F16::from_num(0.0));
    }

    #[test]
    fn test_negative_saturation_recovery() {
        let kp = I16F16::from_num(1.0);
        let ki = I16F16::from_num(0.5);
        let min = I16F16::from_num(-3.0);
        let max = I16F16::from_num(3.0);

        let params = PIParamsPlain::new(kp, ki, min, max);
        let pi = PI::new(params);
        let mut state = PIControllerState::default();

        let error1 = I16F16::from_num(-10.0);
        let output1 = pi.update(error1, &mut state);
        assert_eq!(output1, I16F16::from_num(-3.0));
        assert_eq!(state.integral, I16F16::from_num(0.0));

        let error2 = I16F16::from_num(1.0);
        let output2 = pi.update(error2, &mut state);
        assert_eq!(output2, I16F16::from_num(1.5));
        assert_eq!(state.integral, I16F16::from_num(0.5));
    }

    #[test]
    fn test_positive_saturation_with_negative_recovery() {
        let kp = I16F16::from_num(1.0);
        let ki = I16F16::from_num(0.5);
        let min = I16F16::from_num(-3.0);
        let max = I16F16::from_num(3.0);

        let params = PIParamsPlain::new(kp, ki, min, max);
        let pi = PI::new(params);
        let mut state = PIControllerState::default();

        let error1 = I16F16::from_num(10.0);
        let output1 = pi.update(error1, &mut state);
        assert_eq!(output1, I16F16::from_num(3.0));
        assert_eq!(state.integral, I16F16::from_num(0.0));

        let error2 = I16F16::from_num(-1.0);
        let output2 = pi.update(error2, &mut state);
        assert_eq!(output2, I16F16::from_num(-1.5));
        assert_eq!(state.integral, I16F16::from_num(-0.5));
    }

    #[test]
    fn test_zero_crossing_behavior() {
        let kp = I16F16::from_num(1.0);
        let ki = I16F16::from_num(0.25);
        let min = I16F16::from_num(-5.0);
        let max = I16F16::from_num(5.0);

        let params = PIParamsPlain::new(kp, ki, min, max);
        let pi = PI::new(params);
        let mut state = PIControllerState::default();

        let error1 = I16F16::from_num(1.0);
        let output1 = pi.update(error1, &mut state);
        assert_eq!(output1, I16F16::from_num(1.25));
        assert_eq!(state.integral, I16F16::from_num(0.25));

        let error2 = I16F16::from_num(-2.0);
        let output2 = pi.update(error2, &mut state);
        assert_eq!(output2, I16F16::from_num(-2.25));
        assert_eq!(state.integral, I16F16::from_num(-0.25));
    }

    #[test]
    fn test_conditional_integration_antiwindup_fixed() {
        let kp = I16F16::from_num(1.0);
        let ki = I16F16::from_num(0.1);
        let min = I16F16::from_num(-10.0);
        let max = I16F16::from_num(10.0);

        let params = PIParamsPlain::new(kp, ki, min, max);
        let pi = PI::new(params);
        let mut state = PIControllerState::default();

        let large_error = I16F16::from_num(-50.0);

        let mut integral_mid = I16F16::ZERO;
        let mut integral_final = I16F16::ZERO;

        for i in 0..10 {
            let output = pi.update(large_error, &mut state);
            if i == 5 {
                integral_mid = state.integral;
            }
            if i == 9 {
                integral_final = state.integral;
            }
            assert_eq!(
                output,
                I16F16::from_num(-10.0),
                "Should be saturated at min limit"
            );
        }

        let integral_growth = (integral_final - integral_mid).abs();
        assert!(
            integral_growth < I16F16::from_num(1.0),
            "Integral should stabilize with anti-windup, but grew by {}",
            integral_growth.to_num::<f32>()
        );

        let small_error = I16F16::from_num(-2.0);
        let output_small = pi.update(small_error, &mut state);
        let expected_range = I16F16::from_num(-5.0)..I16F16::from_num(0.0);
        assert!(
            expected_range.contains(&output_small),
            "Output should be reasonable (-5 to 0), got {}",
            output_small.to_num::<f32>()
        );
    }
}
